apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  # namespace: stable-diffusion
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    # eks-tester
    volumeHandle: fs-045ad1b2755f598ef
    volumeAttributes:
      encryptInTransit: "true"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-datadir
  # namespace: stable-diffusion
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 200Gi