apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: public-karpenter
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["c5.large", "c6i.large","m5.large", "m6i.large","r5.large", "r6i.large","c5.xlarge", "c6i.xlarge","m5.xlarge", "m6i.xlarge","r5.xlarge", "r6i.xlarge"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
  taints:
    - key: sd/service
      effect: "NoSchedule"
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: publicnode
  ttlSecondsAfterEmpty: 30
  labels:
      eks/node-type: cpu

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: publicnode
spec:
  tags:
    "eks/node-type": "cpu"
    "auto-delete": "no"
  #select the public subnet
  subnetSelector:
     kubernetes.io/role/elb: "1"
  securityGroupSelector:
    karpenter.sh/discovery: eks-game-gai
  # subnetSelector:
  #   kubernetes.io/role/elb: "1"
  # securityGroupSelector:
  #   karpenter.sh/discovery: eks-tester