apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stable-diffusion-hpa
spec:
  maxReplicas: 2 # Update this according to your desired number of replicas
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: stable-diffusion
  metrics:
  - type: Pods
    pods:
      metric:
        name: DCGM_FI_DEV_GPU_UTIL
      target:
        type: AverageValue
        averageValue: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1 # Scale down to 1 pod
        periodSeconds: 60
